### ISSUE TITLE
Feature request: custom images instead of chars

### ISSUE THREAD

**Issue by janbalaz** [richardtallent/vue-stars#1]
I like idea and simplicity of this plugin, but I'm missing the option to use own images instead of just characters. 
My goal is to use my custom images in a size I provide. I'll keep an eye on this repository. Thank you for your work so far!

**Comment by richardtallent** [comment]
Thanks Jan!

I believe what you're suggesting *should* already be possible by using an `em-space` for both the active and inactive character, then using CSS styling to apply a background-image to `span.active` and `span.inactive` elements. You should even be able to use SVG background images, which could be also styled (or even animated).

I'm open to adding native support for images, if I can figure out how to make the metrics work. For that, I'd either introduce `<img>` tags, or perhaps replace the `character` props with named slots (which also avoids some of the complexities of specifying high-Unicode characters, since slot contents can be encoded.

Good stuff to think about for the next version...

**Comment by janbalaz** [comment]
Thank you Richard, I will look into your suggested solution and use that for now.

I think solution with usage of slots would be very good. I like how [vuex-loading](https://github.com/f/vuex-loading) is done - there is a slot where you can put own custom spinner icon and scale it using _em_ units.

**Comment by richardtallent** [comment]
Hey @janbalaz... just wanted to let you know that Version 1.0 is out, and now scoped/named slots are supported! It's still a little rough--I'm not passing any particular values to the slots, just using them for markup, but based on my very quick test (which is part of the demo page now), it seems to be working.
