### ISSUE TITLE
hoverLabel

### ISSUE THREAD

**Issue by ezhkov** [richardtallent/vue-stars#4]
Hello. Thank you for this great plugin. 
Did you think about adding hover state slot?

**Comment by richardtallent** [comment]
A hover *slot* would require Vue to perform DOM manipulation during mouseenter and mouseleave events. That could lead to some very odd flashing content or other issues.

The current hover interaction is fully CSS-based, which is stable and requires no work on Vue's part. And since CSS can be used to style both HTML and SVG, you can definitely use it to create a custom hover state.

For example, if you're using SVG for your active and inactive slots, you can use an SVG sprite technique, where the hover and non-hover states are named and overlapped in the SVG file, your slot uses the "use" element to assign them a class, and then you can target something like `.vue-stars span.active:hover svg .my-hover-class` to hide and show (or animate) the various states.

If you're using raster graphics or text, it's easy enough to do the same with two elements in each slot and some custom CSS to hide or show the right one when the parent span is hovered.
